POST http://ec2-13-125-96-172.ap-northeast-2.compute.amazonaws.com:3000/api/v1/crawl
Content-Type: application/json

{
  "higher_layer": [
    "cafe", "카페", "coffee", "커피", "일상"
  ],
  "lower_layer": [
    "starbucks", "스타벅스", "daily", "korea", "coffee"
  ],
  "higher_layer_cache": [
    "", "", "", "", ""
  ],
  "lower_layer_cache": [
    "", "", "", "", ""
  ]
}

###

POST http://ec2-13-125-96-172.ap-northeast-2.compute.amazonaws.com:3000/api/v1/crawl
Content-Type: application/json

{
  "higher_layer": [],
  "lower_layer": [
    "starbucks", "스타벅스", "daily", "korea", "coffee"
  ],
  "higher_layer_cache": [],
  "lower_layer_cache": [
    "", "", "", "", ""
  ]
}

###

POST http://ec2-13-125-96-172.ap-northeast-2.compute.amazonaws.com:3000/api/v1/crawl
Content-Type: application/json

{
  "higher_layer": [
    "cafe", "카페", "coffee", "커피", "일상"
  ],
  "lower_layer": [],
  "higher_layer_cache": [
    "", "", "", "", ""
  ],
  "lower_layer_cache": []
}