POST http://13.125.96.172:3000/api/v1/crawl
Content-Type: application/json

{
  "second_layer": [
    "cafe", "카페", "coffee", "커피", "일상"
  ],
  "third_layer": [
    "starbucks", "스타벅스", "daily", "korea", "coffee"
  ],
  "second_layer_cache": [
    "", "", "", "", ""
  ],
  "third_layer_cache": [
    "", "", "", "", ""
  ]
}
