POST http://127.0.0.1:8080/api/v1/crawl
Content-Type: application/json

{
  "second_layer": [
    "cafe", "cafestagram"
  ],
  "third_layer": [
    "starbucks"
  ],
  "second_layer_cache": [
    "", ""
  ],
  "third_layer_cache": [
    ""
  ]
}
